#Numpy is used for scientific opration and it is effiecient and faster

In [55]:
import numpy as np

In [56]:
#one dimensional array
arr=np.array([1,2,3,4,5])
print(arr)
print("shape array",arr.shape)
print("array dimension",arr.ndim)
print("array size",arr.size)
print("the arr datatype is ",arr.dtype)

[1 2 3 4 5]
shape array (5,)
array dimension 1
array size 5
the arr datatype is  int64


In [57]:
#two dimensional array
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1)
print("shape array",arr1.shape)
print("array dimension",arr1.ndim)
print("array size",arr1.size)
print("the arr datatype is ",arr1.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape array (2, 5)
array dimension 2
array size 10
the arr datatype is  int64


In [58]:
#three dimensional array
arr3=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(arr3)
print("shape array",arr3.shape)
print("array dimension",arr3.ndim)
print("array size",arr3.size)
print("the arr datatype is ",arr3.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
shape array (1, 3, 5)
array dimension 3
array size 15
the arr datatype is  int64


In [59]:
#zeros
zero=np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [60]:
#ones
one=np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [61]:
#zeroslike
zerolike=np.zeros_like(arr3,dtype='float32')
print(zerolike)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [62]:
#oneslike
oneslike=np.ones_like(arr3,dtype='float32')
print(oneslike)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [63]:
#empty
empty=np.empty((2,2))
print(empty)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 9.34609111e-307]]


In [64]:
#emptylike
emptylike=np.empty_like(arr3)
print(emptylike)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [65]:
#diagonal matrix
eye=np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
#syntax=> np.arange(start,stop,step)
range_val=np.arange(0,10,2)
print(range_val)

[0 2 4 6 8]


In [67]:
x=np.array([1,2,3])
y=np.array([4,5,6])

#mathematical opration

In [68]:
add_arr=np.add(x,y)
print("addition of two arrays",add_arr)
sub_arr=np.subtract(x,y)
print("subtraction of two arrays",sub_arr)
mul_arr=np.multiply(x,y)
print("multiplication of two arrays",mul_arr)
div_arr=np.divide(x,y)
print("division of two arrays",div_arr)

addition of two arrays [5 7 9]
subtraction of two arrays [-3 -3 -3]
multiplication of two arrays [ 4 10 18]
division of two arrays [0.25 0.4  0.5 ]


In [69]:
arr4=np.array([12,3,34,23,55,39,34])

In [70]:
#return the maximum  value index in the array 
max_index=np.argmax(arr4)
print(max_index)

4


In [71]:
#return the minimum value index in the array 
min_index=np.argmin(arr4)
print(min_index)

1


In [72]:
#reshape the given array
reshape_arr=arr4.reshape(1,7)
print(reshape_arr)

[[12  3 34 23 55 39 34]]


In [73]:
print(x)
print(y)

[1 2 3]
[4 5 6]


In [74]:
#increase the dimension
x=np.expand_dims(x,axis=1)
print(x)

[[1]
 [2]
 [3]]


statistical operation 

In [79]:
cal=np.array([1,2,3,4,5])
print("array is",cal)
print("mean is",np.mean(cal))
print("median is",np.median(cal))
print("standard deviation",np.std(cal))
print("square root",np.sqrt(cal))
print("log",np.log(cal))


array is [1 2 3 4 5]
mean is 3.0
median is 3.0
standard deviation 1.4142135623730951
square root [1.         1.41421356 1.73205081 2.         2.23606798]
log [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [78]:
#np.argsort() sort the array in ascending order
val=([4,7,2,3,8])
sort_array=np.argsort(val)
print(sort_array)

[2 3 0 1 4]


In [90]:
#create random number for every execution
random_num=np.random.randint(0,99)
print(random_num)

66
